### ISSUE TITLE
Trying to fix multiple delete forms with same form id.

### ISSUE THREAD

**Issue by mscraven** [ManatiCR/apachesolr_angularjs_search#15]
Hi guys - Michael Craven at John Hopkins Bloomberg School of Public Health Center for Communication Programs. My boss TJ Moyer posted a message to Basecamp asking about how the delete saved searches and delete search history was not working. We found that only the first search ever deleted on the My Popline search history or saved searches page. Upon inspection, we found that was because all of the delete forms (one per search) have the save form id. I fixed this by Changing the form id in apachesolr_angularjs_search_handler_field_delete_link.inc: 

$form = drupal_get_form('apachesolr_angularjs_search_delete_form_'.$sid, $sid, $link_text);

appending the sid to the form id.

Then, in implementing hook_forms in the main module:

function apachesolr_angularjs_search_forms($form_id, $args) {
   $forms = array();
   if(preg_match('/^apachesolr_angularjs_search_delete_form_\d+/', $form_id)) {
     $forms[$form_id] = array(
                    'callback' => 'apachesolr_angularjs_search_delete_form_callback'
      );
   }
  return $forms;
 }

Then renaming apachesolr_angularjs_search_delete_form as apachesolr_angularjs_search_delete_form_callback and explicitly adding the submit.

 function apachesolr_angularjs_search_delete_form_callback($form, $form_state, $sid, $delete_text) {
   $form['sid'] = array(
     '#type' => 'value',
     '#value' => $sid,
   );

   $form['delete'] = array(
     '#type' => 'submit',
     '#value' => check_plain($delete_text),
   );

   $form['#submit'] = array (
     'apachesolr_angularjs_search_delete_form_submit'
   );
 return $form;
 }
This seemed to fix it.

The second issue was that non autocomplete fields would append an 'AND' and the text that had already been entered when the user hits 'enter.' This problem was fixed by your suggestion on Basecamp:

This appears to be a bug caused by an unexpected event propagation that invokes some code that should never be executed in this context. My advice is to wrap that code and other (I'll provide links) with the next condition:
if ($event.explicitOriginalTarget === $event.target) {}
Jeff Lyon posted a comment about this message on Basecamp
I would wrap:
1) Lines 120 to 123 as in https://github.com/ManatiCR/apachesolr_angularjs_search/blob/7.x-1.x/src/components/booleansPopup/booleansPopup.directive.js#L120
2) Lines 128 to 132 as in https://github.com/ManatiCR/apachesolr_angularjs_search/blob/7.x-1.x/src/components/booleansPopup/booleansPopup.directive.js#L128

Pasting a patch file with these changes. 

Thanks.

[fix_apachesolr_angularjs_search_patch.txt](https://github.com/ManatiCR/apachesolr_angularjs_search/files/178578/fix_apachesolr_angularjs_search_patch.txt)

**Comment by kporras07** [comment]
Hi @mscraven this is great! Could you please submit a Pull Request with these changes? It would be a lot easier to check/test this with a PR

**Comment by kporras07** [comment]
PR Merged, closing issue.
